export const websites = [
    {
        href: 'websites/DueX/index.html',
        src: 'img/websites/dx.png',
        alt: 'DueX - Business Portfolio Website',
        tech: 'Bootstrap 3, JQuery',
        category: 'bootstrap3',
    },
    {
        href: 'websites/Enigma/index.html',
        src: 'img/websites/enigma.png',
        alt: 'Enigma - Modern Business Landing Page',
        tech: 'Bootstrap 3, Less, JQuery',
        category: 'bootstrap3',
    },
    {
        href: 'websites/NomadForce/index.html',
        src: 'img/websites/nomad_force.png',
        alt: 'NomadForce - Travel Agency Website',
        tech: 'Bootstrap 3, Less, JQuery',
        category: 'bootstrap3',
    },
    {
        href: 'websites/PetShop/index.html',
        src: 'img/websites/pet_shop.png',
        alt: 'PetShop - Website for Pet Products',
        tech: 'Bootstrap 3, Less, JQuery',
        category: 'bootstrap3',
    },
    {
        href: 'websites/BuildBetter/index.html',
        src: 'img/websites/build_better.png',
        alt: 'BuildBetter - Furniture Store Website',
        tech: 'Bootstrap 3, Less, JQuery',
        category: 'bootstrap3',
    },
    {
        href: 'websites/Bootstrap/index.html',
        src: 'img/websites/bs.png',
        alt: 'Responsive Layout with Bootstrap 5',
        tech: 'HTML 5, CSS 3, Bootstrap 5',
        category: 'bootstrap5',
    },
    {
        href: 'websites/Motion/index.html',
        src: 'img/websites/motion.png',
        alt: 'Motion - Creative Portfolio Website',
        tech: 'HTML 5, CSS 3, Bootstrap 5',
        category: 'bootstrap5',
    },
    {
        href: 'websites/ION/index.html',
        src: 'img/websites/ion.png',
        alt: 'ION - Simple Responsive Website',
        tech: 'HTML 5, CSS 3',
        category: 'basic',
    },
    {
        href: 'websites/Uniqlo/index.html',
        src: 'img/websites/uniqlo.png',
        alt: 'UNIQLO - Fashion Store Website',
        tech: 'HTML 5, CSS 3',
        category: 'basic',
    },
    {
        href: 'websites/Deals/index.html',
        src: 'img/websites/deals.png',
        alt: 'Hot Deals - Travel Agency Website',
        tech: 'HTML 5, CSS 3',
        category: 'basic',
    },
    {
        href: 'websites/Barber/index.html',
        src: 'img/websites/barber.png',
        alt: 'Barber - Classic Hairstyle Barbershop Website',
        tech: 'HTML 5, CSS 3',
        category: 'basic',
    },
    {
        href: 'http://tomaonlineshop.wuaze.com/users/',
        src: 'img/websites/shop.png',
        alt: 'TOMA - Kids Online Shop',
        tech: 'PHP, MySQL, JQuery, AJAX',
        category: 'php',
    },
    {
        href: 'https://jamesconsulting.netlify.app/',
        src: 'img/websites/jamesconsulting.png',
        alt: 'James Consulting - Developing Innovative Strategies',
        tech: 'TailwindCSS, Vue 3',
        category: 'vue',
    },
    {
        href: 'https://edgecutfurniture.netlify.app/',
        src: 'img/websites/edgecut.png',
        alt: 'Edgecut - Online Furniture Shop',
        tech: 'TailwindCSS, Vue 3',
        category: 'vue',
    },
    // {
    //     href: 'websites/index.html',
    //     src: 'img/websites/.png',
    //     alt: '',
    //     tech: '',
    //     category: '',
    // },
    // {
    //     href: 'websites/index.html',
    //     src: 'img/websites/.png',
    //     alt: '',
    //     tech: '',
    //     category: '',
    // },
];